CREATE ROLE demo PASSWORD 'demo' LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE registration WITH OWNER demo ENCODING = 'UTF8';

\c registration 

CREATE TABLE account(
	id serial PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	registred_date timestamp NOT NULL,
	status CHAR(1) NOT NULL,
	activation_key CHAR(4));

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public  TO demo;
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA public TO demo;
